app/models.py
from flask_login import UserMixin
from app.extensions import bcrypt

class User(UserMixin):
    def __init__(self, email, password, _id):
        self.email = email
        self.password = password
        self.id = _id

    @staticmethod
    def check_password(hashed_password, password):
        return bcrypt.check_password_hash(hashed_password, password)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, Length

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6)])
    submit = SubmitField('Register')

class ComposeForm(FlaskForm):
    to = StringField('To', validators=[DataRequired(), Email()])
    subject = StringField('Subject', validators=[DataRequired()])
    body = TextAreaField('Body', validators=[DataRequired()])
    submit = SubmitField('Send')

app/__init__.py
from flask import Flask
from app.extensions import bcrypt, login_manager, mongo
from bson import ObjectId
from app.models import User
from dotenv import load_dotenv
import os

load_dotenv()  # Load environment variables from .env file

def create_app():
    app = Flask(__name__)
    app.config.from_object('config.Config')

    bcrypt.init_app(app)
    login_manager.init_app(app)
    mongo.init_app(app)

    from app.routes import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

@login_manager.user_loader
def load_user(user_id):
    user_data = mongo.db.users.find_one({"_id": ObjectId(user_id)})
    if user_data:
        return User(email=user_data['email'], password=user_data['password'], _id=user_data['_id'])
    return None

app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, logout_user, login_required, current_user
from app import bcrypt, mongo
from app.forms import LoginForm, RegistrationForm, ComposeForm
from app.models import User
from bson.objectid import ObjectId

main = Blueprint('main', __name__)

@main.route('/')
def home():
    if current_user.is_authenticated:
        return redirect(url_for('main.inbox'))
    return redirect(url_for('main.login'))

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user_data = mongo.db.users.find_one({'email': email})
        if user_data and bcrypt.check_password_hash(user_data['password'], password):
            user = User(email=user_data['email'], password=user_data['password'], _id=str(user_data['_id']))
            login_user(user)
            flash('Login successful!', 'success')
            return redirect(url_for('main.inbox'))
        else:
            flash('Invalid email or password', 'danger')
    return render_template('login.html', form=form)

@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = {
            'email': form.email.data,
            'password': hashed_password
        }
        mongo.db.users.insert_one(user)
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form)

@main.route('/compose', methods=['GET', 'POST'])
@login_required
def compose():
    form = ComposeForm()
    if form.validate_on_submit():
        email = {
            'from': current_user.email,
            'to': form.to.data,
            'subject': form.subject.data,
            'body': form.body.data,
            'timestamp': request.form.get('timestamp')
        }
        mongo.db.emails.insert_one(email)
        flash('Email sent!', 'success')
        return redirect(url_for('main.inbox'))
    return render_template('compose.html', form=form)

@main.route('/inbox')
@login_required
def inbox():
    emails = mongo.db.emails.find({'to': current_user.email})
    return render_template('inbox.html', emails=emails)

@main.route('/sent')
@login_required
def sent():
    emails = mongo.db.emails.find({'from': current_user.email})
    return render_template('sent.html', emails=emails)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('main.login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Email App{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{{ url_for('main.inbox') }}">Inbox</a></li>
            <li><a href="{{ url_for('main.sent') }}">Sent</a></li>
            <li><a href="{{ url_for('main.compose') }}">Compose</a></li>
            <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
        </ul>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/compose.html
{% extends "base.html" %}
{% block title %}Compose{% endblock %}
{% block content %}
    <h2>Compose Email</h2>
    <form method="POST" action="{{ url_for('main.compose') }}">
        {{ form.hidden_tag() }}
        <div>
            {{ form.to.label }}<br>
            {{ form.to(size=32) }}<br>
            {{ form.to.errors }}
        </div>
        <div>
            {{ form.subject.label }}<br>
            {{ form.subject(size=32) }}<br>
            {{ form.subject.errors }}
        </div>
        <div>
            {{ form.body.label }}<br>
            {{ form.body(rows=10, cols=32) }}<br>
            {{ form.body.errors }}
        </div>
        <div>
            {{ form.submit() }}
        </div>
    </form>
{% endblock %}

app/templates/inbox.html
{% extends "base.html" %}
{% block title %}Inbox{% endblock %}
{% block content %}
    <h2>Inbox</h2>
    <ul>
        {% for email in emails %}
            <li>{{ email.subject }} - {{ email.body }}</li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <h2>Login</h2>
    <form method="POST" action="{{ url_for('main.login') }}">
        {{ form.hidden_tag() }}
        <div>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {{ form.email.errors }}
        </div>
        <div>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {{ form.password.errors }}
        </div>
        <div>
            {{ form.submit() }}
        </div>
    </form>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Register</h5>
                    <form method="POST" action="{{ url_for('main.register') }}">
                        {{ form.hidden_tag() }}
                        <div>
                            {{ form.email.label }}<br>
                            {{ form.email(size=32) }}<br>
                            {{ form.email.errors }}
                        </div>
                        <div>
                            {{ form.password.label }}<br>
                            {{ form.password(size=32) }}<br>
                            {{ form.password.errors }}
                        </div>
                        <div>
                            {{ form.submit() }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/sent.html
{% extends "base.html" %}
{% block title %}Sent{% endblock %}
{% block content %}
    <h2>Sent</h2>
    <ul>
        {% for email in emails %}
            <li>{{ email.subject }} - {{ email.body }}</li>
        {% endfor %}
    </ul>
{% endblock %}